### ISSUE TITLE
Routes not defined

### ISSUE THREAD

**Issue by mnwalker** [caffeinated/modules#432]
Have just upgraded an app from laravel 5.1 to laravel 6.0
Modules from 2.1 to 6.1

Worked through the bulk of issues already and now stuck on module routes being undeclared.

```
local.ERROR: Route [admin.event.alert.index] not defined. {"userId":1,"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [admin.event.alert.index] not defined. at /core/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:420)
[stacktrace]
#0 /src/core/app/Http/helpers.php(41): Illuminate\\Routing\\UrlGenerator->route('admin.event.ale...', Array, true, NULL)
#1 /src/modules/Events/Events.php(133): route('admin.event.ale...')
#2 /src/core/app/Http/Controllers/BaseController.php(191): 
```

This was also being triggered with artisan commands but resolved that.
Had to remove some route() links that were being set during controller constructs
Some could stay in, some caused the error - guessing this is due to order of the module loading?

Another instance is in a Modules main file, again removing route gets it a stage further.

Is there anything I can add to the service provider or similar to ensure that all route, for all modules are registered, before it starts to execute main code?

Was working fine in the old version so some logic or function has changed in the later versions.

**Comment by mnwalker** [comment]
Ignore this.
For reference incase anyone experiences similar was due to core laravel changes in how to name routes between old Controller:: and newer Resource:: formats.
